fix: doc comments regarding safety for `Number.toU32()`
Discovered this while working on https://github.com/ChainSafe/lodestar-z/pull/349.

`napi_get_value_uint32` makes no guarantee of erroring on values out of
bounds:

> Let int32bit be int modulo 2**32.

Source: https://tc39.es/ecma262/#sec-touint32

This little code snippet PoC when added to `BeaconStateView.test.ts` in
lodestar-z passes:

```ts
  it("toU32 silently wraps around", () => {
    let i = 0;
    for (i = 0; i < 100; i++) {
      const a = state.getBalance(0 + i);
      const b = state.getBalance(2 ** 32 + i);
      expect(a).toBe(b);    
      }
  });
```

While this fails, but only because we're access the SSZ list index out of
bounds:

```ts
state.getBalance(-1)
```

```
 FAIL  bindings/test/beaconStateView.test.ts > BeaconStateView > probe truncation behavior
Error: IndexOutOfBounds
```

Other conversion methods might behave the same; i haven't fully checked,
but we should be careful of this